#!/usr/bin/env bash
#
# Created By: stephansarver
# Created Date: 20180531-092037
#
# set -o errexit
# set -o errtrace
set -o nounset

clear

#Initialize the command switches
cmd_switch_check_uncommitted="-c"
cmd_switch_delete_config="-d"
cmd_switch_git_fetch="-f"
cmd_switch_show_repo_list="-l"
cmd_switch_git_pull="-p"
cmd_switch_update_repo_list="-u"
cmd_switch_set_config_for_current_repos="-m"

# TODO: Figure out how to do this
# cmd_switch_display_review_requests="-r"

github_user=""
github_org_name=""
github_api_base="https://api.github.com"
github_repo_base="https://github.com/"
github_api_per_page="100"

file_name_for_config=".gitdir_conf"
file_name_for_repos=".gitdir_repos"
file_name_for_skip_repos=".gitdir_skip_repos"

#repos=()

function usage(){
  echo "USAGE:"
  echo " "
  echo "  Name: gitdir"
  echo " "
  echo "  Description: "
  echo "      This script is used to handle some basic batch git functions for a organizations git repositories."
  echo "      The script will store in hidden files the github organization name and github user name so it does"
  echo "      not have to be re-entered each time the script is run. This script will also store in a hidden file "
  echo "      a list of repos that were looked up for the organization that the user has access to."
  echo "      See additional notes below."
  echo " "
  echo " "
  echo "  Command Switches:"
  echo "      -c Used to check for repos with uncommitted files."
  echo "      -d Used to delete locally stored configuration and start new."
  echo "      -f Used to fetch and update the local git indexes for the repositories."
  echo "      -l Used to show the list of cloned repositories."
  echo "      -p Used to pull the latested currently checked out versions of the repositories."
  echo "      -u Used for updating the locally cached repository list."
  echo "      -m Match or set the gitdir config for the currently cloned repos(do not pull all from org)."

  # TODO: Figure out how to do this
  # echo "      -r Used for listing review requests."
  echo " "
}

function throw_error(){
  local_param_property=$1
  local_param_message=$2

  echo "********************"
  echo "Error: "
  echo " "
  echo "  $local_param_property $local_param_message "
  echo " "
  echo "********************"
  exit 1
}

function populate_repo_list {
  local page_count=1
  local repo_count=0
  rm "$file_name_for_repos"
  touch "$file_name_for_repos"
  # curl --user "$github_user" "$github_api_base/orgs/$github_org_name/repos?per_page=100&page=2" | jq -r ".[].name" >"$file_name_for_repos"

  while [ "$(expr $repo_count % $github_api_per_page)" == "0" ]
  do
    curl --user "$github_user" "$github_api_base/orgs/$github_org_name/repos?page=$page_count&per_page=$github_api_per_page" | jq -r ".[].name" >>"$file_name_for_repos"
    repo_count=$(wc -l < "$file_name_for_repos")
    page_count=$((page_count+1))
  done
}

# Iterate local directorry and only add to config directories that have a .git directory!
function populate_cloned_repo_list {
  rm "$file_name_for_repos"
  touch "$file_name_for_repos"
  for dir in $(ls)
  do
    if [ -d "$dir" ]; then
      for nesteddir in $(ls -a $dir)
      do
        if [ ".git" == "$nesteddir" ]; then
          echo "Setting - $dir"
          echo "$dir" >>"$file_name_for_repos"
        fi
      done
    fi
  done
}

function delete_git_config {
  echo "You are about to delete your saved github organization name and github user name you will have to re-enter this the next time you run this script are you sure you want to proceed?"
  read -r delete_config
  if [[ "y" == "$delete_config" || "Y" == "$delete_config" || "yes" == "$delete_config" || "YES" == "$delete_config" || "Yes" == "$delete_config" ]]; then
    if [ -f "$file_name_for_config" ]; then
      rm "$file_name_for_config"
    else
      echo "The config file does not exist and could not be deleted: $file_name_for_config"
    fi
  else
    throw_error "Aborted deleteing gitdir config." "$delete_config"
  fi
}

function load_git_config {
  if [ ! -f "$file_name_for_config" ]; then
    echo "Creating git config file"
    create_git_config
  fi

  if [ -f "$file_name_for_config" ]; then
    echo "loading from git config file"
    gitdir_config=$(cat $file_name_for_config)
    echo "$gitdir_config"

    #declare -a gitdir_configs=(${gitdir_config//|/ })

    OLDIFS=$IFS
    IFS='|' read -r -a gitdir_configs <<< "$gitdir_config"
    IFS=$OLDIFS

    github_org_name="${gitdir_configs[0]}"
    github_user="${gitdir_configs[1]}"
  fi

  if [[ "" == "$github_user"  || "" == "$github_org_name" ]]; then
    echo "Storing to git config file"
    create_git_config
  fi
}

function create_git_config {
  echo " "
  echo "Please enter the github organization name and hit enter:"
  read -r github_org_name
  echo " "
  echo "Please enter your github user name and hit enter:"
  read -r github_user
  echo "You have entered the following values:"
  echo "  github organization: $github_org_name"
  echo "  github user: $github_user"
  echo " "
  echo "Are these correct?"
  read -r correct_entries
  if [[ "y" == "$correct_entries" || "Y" == "$correct_entries" || "yes" == "$correct_entries" || "YES" == "$correct_entries" || "Yes" == "$correct_entries" ]]; then
    touch "$file_name_for_config"
    echo "$github_org_name|$github_user">"$file_name_for_config"
  else
    throw_error "Aborting saving github organization and username."
  fi
}

function pull_repos {
  fetch_repos "y"
}

function fetch_repos {
  count=0
  pull_current_branch="$1"
  while read -r repo; do
    skip_repo_processing='false'
    message="Repo: $repo"
    repo_cloned="false"
    for directory in *
    do
      if [[ -d $directory ]]; then
        if [[ "$directory" == "$repo" ]]; then
          if [ -f "$file_name_for_skip_repos" ]; then
            while read -r skip_repo; do
              if [ "$repo" == "$skip_repo" ]; then
                skip_repo_processing='true'
              fi
            done <"$file_name_for_skip_repos"
          fi
          count=$((count+1))
          if [ "true" ==  "$skip_repo_processing" ]; then
            echo "***** - $message - $count Skipping processing!"
          else
            message="$message - $count - Found - fetching from git"
            if [[ "y" == "$pull_current_branch" ]]; then
              message="$message - pulling latest into current branch."
            fi
            pushd . > /dev/null 2>&1
            cd "$repo" > /dev/null 2>&1
            echo "$message"
            git fetch --all
            if [[ "y" == "$pull_current_branch" ]]; then
              git pull
            fi
            repo_cloned="true"
            popd > /dev/null 2>&1
          fi
          repo_cloned="true"
          popd > /dev/null 2>&1
        fi
      fi
    done
    if [[ "false" ==  "$skip_repo_processing" ]]; then
      if [[ "false" == "$repo_cloned" ]] ; then
        echo "$message not found, cloning! - $count"
        git clone "$github_repo_base$github_org_name/$repo.git"
      fi
    fi
    echo " "
  done <"$file_name_for_repos"
}

function check_for_uncommitted {
  no_local_changes_found="true"
  while read -r repo; do
    for directory in *
    do
      if [[ -d $directory ]]; then
        if [[ "$directory" == "$repo" ]]; then
          pushd . > /dev/null 2>&1
          cd "$repo" > /dev/null 2>&1
          status="$(git status)"
          if [[ "$status" == *"Changes not staged for commit"* || "$status" == *"Untracked files"* ]]; then
            echo " "
            echo " "
            echo "--------------------------------------"
            echo "$repo : Local changes found!"
            echo "--------------------------------------"
            echo "$status"
            no_local_changes_found="false"
          fi
          popd > /dev/null 2>&1
        fi
      fi
    done

  done <"$file_name_for_repos"
  if [ "true" == "$no_local_changes_found" ]; then
    echo " "
    echo "No changes found!"
    echo " "
  fi

}

function show_repo_list {
    cat "$file_name_for_repos"
}


# TODO: Figure out how to do this
# function list_review_requests {
#   echo "---- List open review requests ----"
#   echo  " "
#   # echo "Implement me!!!"
#
#   # URL="https://github.com/pulls/review-requested"
#   # URL="https://github.com/pulls?q=is%3Aopen+is%3Apr+review-requested%3Ascsarver+archived%3Afalse+user%3Aopploans"
#   # curl -L  --user "$github_user" "$URL"
#
#   #https://developer.github.com/v3/search/
#   #https://github.com/pulls/review-requested
#
#   # curl --user "$github_user" "$github_api_base/orgs/$github_org_name/repos?per_page=100" | jq -r ".[].name" >"$file_name_for_repos"
#   # curl -v -H "Authorization: token TOKEN" https://api.github.com/search/issues?q=is:open+is:pr+review-requested:"$github_user"
#   # curl -v --user "$github_user" "$github_api_base/orgs/$github_org_name/search/issues?q=is:open+is:pr+review-requested:$github_user"
#
#   #is:open is:pr review-requested:scsarver archived:false
#   # curl -L -v --user "$github_user" "https://github.com/pulls/review-requested"
#
#
#   # SEARCH_PATH="/search/pulls"
#   # SEARCH_STRING="q=is:open+is:pr+review-requested:$github_user+archived:false+org:$github_org_name"
#   # echo " "
#   # echo "Requesting: ${github_api_base}${SEARCH_PATH}?${SEARCH_STRING}"
#
#   # curl -v --user "$github_user" -H "application/vnd.github.symmetra-preview+json" "$github_api_base/orgs/$github_org_name/search/pulls?q=is:open+is:pr+review-requested:$github_user"
#   # curl --user "$github_user" -H "application/vnd.github.symmetra-preview+json" "$github_api_base/search/pulls?q=is:open+is:pr+review-requested:$github_user"
#   # curl --user "$github_user" "${github_api_base}/search/pulls?q=is:open+is:pr+review-requested:$github_user"
#
#   # curl --user "$github_user" "${github_api_base}${SEARCH_PATH}?${SEARCH_STRING}"
#   # | jq -r '.items[] | .url'
# }



#Start processing by checking for command switches if there are none print usage and exit.
if [[ "" == "$*" ]]; then
  usage
  exit 1
fi

for arg in "$@"
do
  if [[ "$arg" == "$cmd_switch_check_uncommitted" ]]; then
    echo "---- Checking repos for uncommitted files ----"
    check_for_uncommitted
  elif [[ "$arg" == "$cmd_switch_delete_config" ]]; then
    echo "---- Deleting gitdir config! ---- "
    delete_git_config
  elif [[ "$arg" == "$cmd_switch_git_fetch" ]]; then
    echo "---- Executing gitdir fetch! ---- "
    load_git_config
    fetch_repos "n"
  elif [[ "$arg" == "$cmd_switch_show_repo_list" ]]; then
    echo "---- Show gitdir repo list! ---- "
    show_repo_list
  elif [[ "$arg" == "$cmd_switch_git_pull" ]]; then
    echo "---- Executing gitdir pull! ---- "
    load_git_config
    pull_repos
  elif [[ "$arg" == "$cmd_switch_set_config_for_current_repos" ]]; then
    echo "---- Executing gitdir set the gitdir config for the currently cloned repos(do not pull all from org) ---- "
    load_git_config
    populate_cloned_repo_list
  elif [[ "$arg" == "$cmd_switch_update_repo_list" ]]; then
    echo "---- Executing gitdir update repo list! ---- "
    load_git_config
    populate_repo_list
  # elif [[ "$arg" == "$cmd_switch_display_review_requests" ]]; then
  #   echo "---- Executing gitdir list review requests! ---- "
  #   load_git_config
  #   list_review_requests
  else
    usage
    throw_error "Unexpected parameter found:" "$arg"
  fi
done

echo " "
echo "_______________________________"
echo "Completed: $(date +%Y.%m.%d-%H:%M:%S)"
echo " "
